package UI_admin;


import AdminPerpus.DaftarAdmin;
import AdminPerpus.Admin;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class daftar_admin extends javax.swing.JFrame {

    /**
     * Creates new form daftar_admin
     */
    public daftar_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        daftarnamaaadmin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        daftarnip = new javax.swing.JTextField();
        isiusername = new javax.swing.JLabel();
        daftarusername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        daftaradmin = new javax.swing.JButton();
        daftarpassword = new javax.swing.JPasswordField();
        canceldaftar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME!!!");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 420, 90);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 90, 40, 14);
        jLabel2.getAccessibleContext().setAccessibleName("nama");

        daftarnamaaadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarnamaaadminActionPerformed(evt);
            }
        });
        getContentPane().add(daftarnamaaadmin);
        daftarnamaaadmin.setBounds(10, 110, 170, 27);
        daftarnamaaadmin.getAccessibleContext().setAccessibleName("nama");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("NIP");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 140, 31, 14);

        daftarnip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarnipActionPerformed(evt);
            }
        });
        getContentPane().add(daftarnip);
        daftarnip.setBounds(10, 160, 170, 27);
        daftarnip.getAccessibleContext().setAccessibleName("nip");

        isiusername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        isiusername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        isiusername.setText("Username");
        getContentPane().add(isiusername);
        isiusername.setBounds(280, 90, 70, 15);

        daftarusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarusernameActionPerformed(evt);
            }
        });
        getContentPane().add(daftarusername);
        daftarusername.setBounds(240, 110, 170, 29);
        daftarusername.getAccessibleContext().setAccessibleName("username");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 140, 80, 15);

        daftaradmin.setText("DAFTAR");
        daftaradmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftaradminActionPerformed(evt);
            }
        });
        getContentPane().add(daftaradmin);
        daftaradmin.setBounds(100, 290, 90, 30);

        daftarpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(daftarpassword);
        daftarpassword.setBounds(240, 160, 170, 30);

        canceldaftar.setText("CANCEL");
        canceldaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceldaftarActionPerformed(evt);
            }
        });
        getContentPane().add(canceldaftar);
        canceldaftar.setBounds(240, 290, 80, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/IMG_20190221_230808.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 420, 400);

        setSize(new java.awt.Dimension(437, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void daftarnamaaadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarnamaaadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daftarnamaaadminActionPerformed

    private void daftaradminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftaradminActionPerformed
        // TODO add your handling code here:
        
            DaftarAdmin sp = new DaftarAdmin(
                
                new Admin(
                    daftarnip.getText(),
                    daftarnamaaadmin.getText(),
                    daftarusername.getText(),
                    daftarpassword.getText()
                )
                
            );
            if(sp.validasiData()){
                if(sp.getDaftar()!=-1){
                    new menuadmin().setVisible(true);
                    this.setVisible(false);
                }
            }else{
                sp.Pesan("Data Tidak Valid!");
            }
           
    }//GEN-LAST:event_daftaradminActionPerformed

    private void daftarnipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarnipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daftarnipActionPerformed

    private void daftarusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daftarusernameActionPerformed

    private void daftarpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daftarpasswordActionPerformed

    private void canceldaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceldaftarActionPerformed
        // TODO add your handling code here:
        new menuadmin ().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_canceldaftarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftar_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftar_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftar_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftar_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canceldaftar;
    private javax.swing.JButton daftaradmin;
    private javax.swing.JTextField daftarnamaaadmin;
    private javax.swing.JTextField daftarnip;
    private javax.swing.JPasswordField daftarpassword;
    private javax.swing.JTextField daftarusername;
    private javax.swing.JLabel isiusername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
