package UI_admin;

import Database.conek;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class login1 extends javax.swing.JFrame {
    public login1() {
        initComponents();
        loginawal.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginawal = new javax.swing.JPanel();
        login_mhs = new javax.swing.JLabel();
        LOGIN_admin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        login_admin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        loginadmin = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        cancelloginadmin = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        loginmhs_ = new javax.swing.JPanel();
        login_admin1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idlogin = new javax.swing.JTextField();
        LOG_mhs = new javax.swing.JButton();
        LOG_dosen = new javax.swing.JButton();
        cancelloginmhs = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));
        getContentPane().setLayout(new java.awt.CardLayout());

        loginawal.setBackground(new java.awt.Color(255, 255, 255));
        loginawal.setLayout(null);

        login_mhs.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        login_mhs.setForeground(new java.awt.Color(255, 255, 255));
        login_mhs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_mhs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/anggota.png"))); // NOI18N
        login_mhs.setText("Mahasiswa");
        login_mhs.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        login_mhs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        login_mhs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        login_mhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mahasiswa(evt);
            }
        });
        loginawal.add(login_mhs);
        login_mhs.setBounds(300, 190, 100, 115);

        LOGIN_admin.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        LOGIN_admin.setForeground(new java.awt.Color(255, 255, 255));
        LOGIN_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/admin.png"))); // NOI18N
        LOGIN_admin.setText("Admin");
        LOGIN_admin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LOGIN_admin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        LOGIN_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGIN_adminMouseClicked(evt);
            }
        });
        loginawal.add(LOGIN_admin);
        LOGIN_admin.setBounds(130, 190, 90, 115);

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PERPUSTAKAAN ITERA");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginawal.add(jLabel1);
        jLabel1.setBounds(0, 0, 529, 145);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/y11.jpg"))); // NOI18N
        loginawal.add(jLabel7);
        jLabel7.setBounds(0, -30, 530, 480);

        getContentPane().add(loginawal, "card3");

        login_admin.setBackground(new java.awt.Color(255, 255, 255));
        login_admin.setToolTipText("");
        login_admin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        login_admin.setMinimumSize(new java.awt.Dimension(0, 0));
        login_admin.setName(""); // NOI18N
        login_admin.setPreferredSize(new java.awt.Dimension(325, 400));
        login_admin.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 102, 102));
        jLabel2.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOGIN ADMIN");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setMaximumSize(new java.awt.Dimension(100, 25));
        jLabel2.setMinimumSize(new java.awt.Dimension(100, 25));
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 50));
        login_admin.add(jLabel2);
        jLabel2.setBounds(120, 10, 340, 110);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("UserName");
        login_admin.add(jLabel3);
        jLabel3.setBounds(180, 170, 60, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Password");
        login_admin.add(jLabel4);
        jLabel4.setBounds(180, 220, 60, 15);

        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setMinimumSize(new java.awt.Dimension(6, 30));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        login_admin.add(password);
        password.setBounds(270, 210, 120, 30);

        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        login_admin.add(username);
        username.setBounds(270, 160, 120, 30);

        loginadmin.setText("Login");
        loginadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginadminActionPerformed(evt);
            }
        });
        login_admin.add(loginadmin);
        loginadmin.setBounds(200, 310, 60, 30);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        login_admin.add(exit);
        exit.setBounds(300, 310, 60, 30);

        cancelloginadmin.setText("Cancel");
        cancelloginadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelloginadminActionPerformed(evt);
            }
        });
        login_admin.add(cancelloginadmin);
        cancelloginadmin.setBounds(240, 380, 80, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/c.jpg"))); // NOI18N
        login_admin.add(jLabel8);
        jLabel8.setBounds(0, 0, 550, 450);

        getContentPane().add(login_admin, "card2");

        login_admin1.setBackground(new java.awt.Color(255, 255, 255));
        login_admin1.setToolTipText("");
        login_admin1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        login_admin1.setName(""); // NOI18N
        login_admin1.setPreferredSize(new java.awt.Dimension(325, 400));
        login_admin1.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(255, 102, 102));
        jLabel5.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("LOGIN ANGGOTA");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setMaximumSize(new java.awt.Dimension(100, 25));
        jLabel5.setMinimumSize(new java.awt.Dimension(100, 25));
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 50));
        login_admin1.add(jLabel5);
        jLabel5.setBounds(90, 27, 358, 78);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("NIP/NIM");
        login_admin1.add(jLabel6);
        jLabel6.setBounds(190, 190, 70, 30);

        idlogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idloginActionPerformed(evt);
            }
        });
        login_admin1.add(idlogin);
        idlogin.setBounds(270, 190, 110, 30);

        LOG_mhs.setText("Mahasiswa");
        LOG_mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOG_mhsActionPerformed(evt);
            }
        });
        login_admin1.add(LOG_mhs);
        LOG_mhs.setBounds(180, 303, 100, 30);

        LOG_dosen.setText("Dosen");
        LOG_dosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOG_dosenActionPerformed(evt);
            }
        });
        login_admin1.add(LOG_dosen);
        LOG_dosen.setBounds(300, 303, 100, 30);

        cancelloginmhs.setText("Cancel");
        cancelloginmhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelloginmhsActionPerformed(evt);
            }
        });
        login_admin1.add(cancelloginmhs);
        cancelloginmhs.setBounds(260, 370, 70, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/c.jpg"))); // NOI18N
        login_admin1.add(jLabel9);
        jLabel9.setBounds(0, 0, 530, 450);

        javax.swing.GroupLayout loginmhs_Layout = new javax.swing.GroupLayout(loginmhs_);
        loginmhs_.setLayout(loginmhs_Layout);
        loginmhs_Layout.setHorizontalGroup(
            loginmhs_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
            .addGroup(loginmhs_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(login_admin1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE))
        );
        loginmhs_Layout.setVerticalGroup(
            loginmhs_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
            .addGroup(loginmhs_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(login_admin1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE))
        );

        getContentPane().add(loginmhs_, "card4");

        setSize(new java.awt.Dimension(545, 485));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//GEN-FIRST:event_loginadminActionPerformed
 private void loginadminActionPerformed(java.awt.event.ActionEvent evt) {                                         
        try{
            Statement statement = (Statement) conek.GetConnection().createStatement();
            ResultSet result = statement.executeQuery("select * from admin where " + "username='" + username.getText()+ "'" );
            if(result.next()){
                ResultSet result2 = statement.executeQuery("select * from admin where " + "password='" + password.getText()+"'");
                if(result2.next()){
                    new menuadmin(username.getText()).setVisible(true);
                    this.setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Password Salah");
                    password.setText("");
                    username.requestFocus();
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "User Tidak ditermukan");
                username.setText("");
                password.setText("");
                username.requestFocus();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "gagal");
        }
           
    }
//GEN-LAST:event_loginadminActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void mahasiswa(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mahasiswa
        // TODO add your handling code here:
        loginawal.setVisible(false);
        loginmhs_.setVisible(true);
    }//GEN-LAST:event_mahasiswa

    private void LOGIN_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGIN_adminMouseClicked
        
        login_admin.setVisible(true);
        loginawal.setVisible(false);
    }//GEN-LAST:event_LOGIN_adminMouseClicked

    private void idloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idloginActionPerformed

    private void LOG_mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOG_mhsActionPerformed
        try{
            Statement statement1 = (Statement) conek.GetConnection().createStatement();
            ResultSet result1 = statement1.executeQuery("select * from mahasiswa where " + "NIM='" +idlogin.getText()+"'" );
            if(result1.next()){
                new menuAnggota().setVisible(true);
                this.setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Anda belum terdaftar sebagai anggota atau Salah Submit");
                    idlogin.setText("");
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "gagal");
        }
           
    }//GEN-LAST:event_LOG_mhsActionPerformed

    private void LOG_dosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOG_dosenActionPerformed
        try{
            Statement statement1 = (Statement) conek.GetConnection().createStatement();
            ResultSet result1 = statement1.executeQuery("select * from dosen where " + "NIP='" +idlogin.getText()+"'" );
            if(result1.next()){
                new menuAnggota().setVisible(true);
                this.setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Anda belum terdaftar sebagai anggota atau Salah Submit");
                    idlogin.setText("");
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "gagal");
        }
    }//GEN-LAST:event_LOG_dosenActionPerformed

    private void cancelloginadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelloginadminActionPerformed
        loginawal.setVisible(true);
        login_admin.setVisible(false);
    }//GEN-LAST:event_cancelloginadminActionPerformed

    private void cancelloginmhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelloginmhsActionPerformed
        loginawal.setVisible(true);
        loginmhs_.setVisible(false);
    }//GEN-LAST:event_cancelloginmhsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGIN_admin;
    private javax.swing.JButton LOG_dosen;
    private javax.swing.JButton LOG_mhs;
    private javax.swing.JButton cancelloginadmin;
    private javax.swing.JButton cancelloginmhs;
    private javax.swing.JButton exit;
    private javax.swing.JTextField idlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel login_admin;
    private javax.swing.JPanel login_admin1;
    private javax.swing.JLabel login_mhs;
    private javax.swing.JButton loginadmin;
    private javax.swing.JPanel loginawal;
    private javax.swing.JPanel loginmhs_;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
