/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_admin;

import Anggota.TableDosen;
import Anggota.TableMahasiswa;
import Buku.TableBuku;
import Peminjaman.TablePeminjaman;

/**
 *
 * @author ASUS
 */
public class menuAnggota extends javax.swing.JFrame {

    /**
     * Creates new form menuMahasiswa
     */
    public menuAnggota() {
        initComponents();
        Menuawal.setVisible(true);
        tampilDataBuku.setVisible(false);
        tampildatamhs.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menuawal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        caribuku = new javax.swing.JLabel();
        caridosen = new javax.swing.JLabel();
        pinjam = new javax.swing.JLabel();
        carimhs = new javax.swing.JLabel();
        logoutmhs = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tampilDataBuku = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cancelMeuTampilBuku = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        caribuku_ = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cari_buku = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tampildatamhs = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        cancelMeuMhs2 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelmhs2 = new javax.swing.JTable();
        Mhs_cari2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        cari_mhs2 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tampildatadosen = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cancelMenudosen = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabledosen = new javax.swing.JTable();
        dosen_cari = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cari_anggota = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        peminjaman = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        cancelMenuPinjam = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelpinjam = new javax.swing.JTable();
        jLabel35 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        Menuawal.setBackground(new java.awt.Color(255, 255, 255));
        Menuawal.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Eras Bold ITC", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PERPUSTAKAAN ITERA");
        Menuawal.add(jLabel2);
        jLabel2.setBounds(270, 60, 650, 104);

        caribuku.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        caribuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/Background.png"))); // NOI18N
        caribuku.setText("Cari Buku");
        caribuku.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        caribuku.setVerifyInputWhenFocusTarget(false);
        caribuku.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        caribuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caribukuMouseClicked(evt);
            }
        });
        Menuawal.add(caribuku);
        caribuku.setBounds(640, 390, 96, 143);

        caridosen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        caridosen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        caridosen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/dosen.png"))); // NOI18N
        caridosen.setText("Cari Dosen");
        caridosen.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        caridosen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        caridosen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        caridosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caridosenMouseClicked(evt);
            }
        });
        Menuawal.add(caridosen);
        caridosen.setBounds(800, 320, 103, 143);

        pinjam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pinjam.setForeground(new java.awt.Color(255, 255, 255));
        pinjam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pinjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/pinjambuku.png"))); // NOI18N
        pinjam.setText("Peminjaman Buku");
        pinjam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pinjam.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pinjamMouseClicked(evt);
            }
        });
        Menuawal.add(pinjam);
        pinjam.setBounds(430, 370, 112, 168);

        carimhs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        carimhs.setForeground(new java.awt.Color(255, 255, 255));
        carimhs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carimhs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/STIKER_KARTUN_WISUDA_4.jpg"))); // NOI18N
        carimhs.setText("Cari Mahasiswa");
        carimhs.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        carimhs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        carimhs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        carimhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carimhsMouseClicked(evt);
            }
        });
        Menuawal.add(carimhs);
        carimhs.setBounds(240, 320, 103, 143);

        logoutmhs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logoutmhs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/Logout-icon.png"))); // NOI18N
        logoutmhs.setText("Log Out");
        logoutmhs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoutmhs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        logoutmhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutmhsMouseClicked(evt);
            }
        });
        Menuawal.add(logoutmhs);
        logoutmhs.setBounds(960, 510, 68, 83);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/a11.jpg"))); // NOI18N
        Menuawal.add(jLabel3);
        jLabel3.setBounds(-10, 0, 1170, 690);

        getContentPane().add(Menuawal, "card2");

        tampilDataBuku.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        cancelMeuTampilBuku.setText("CANCEL");
        cancelMeuTampilBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelMeuTampilBukuActionPerformed(evt);
            }
        });
        jPanel3.add(cancelMeuTampilBuku);
        cancelMeuTampilBuku.setBounds(370, 470, 145, 23);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(510, 250, 546, 188);
        jPanel3.add(caribuku_);
        caribuku_.setBounds(190, 250, 150, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cari Buku");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(60, 250, 100, 30);

        cari_buku.setText("CARI");
        cari_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_bukuActionPerformed(evt);
            }
        });
        jPanel3.add(cari_buku);
        cari_buku.setBounds(190, 310, 70, 30);

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("CARI DATA BUKU");
        jPanel3.add(jLabel36);
        jLabel36.setBounds(359, 110, 400, 160);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/perpustera.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 0, 1140, 740);

        javax.swing.GroupLayout tampilDataBukuLayout = new javax.swing.GroupLayout(tampilDataBuku);
        tampilDataBuku.setLayout(tampilDataBukuLayout);
        tampilDataBukuLayout.setHorizontalGroup(
            tampilDataBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tampilDataBukuLayout.setVerticalGroup(
            tampilDataBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        getContentPane().add(tampilDataBuku, "card3");

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(null);

        cancelMeuMhs2.setText("CANCEL");
        cancelMeuMhs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelMeuMhsActionPerformed(evt);
            }
        });
        jPanel8.add(cancelMeuMhs2);
        cancelMeuMhs2.setBounds(170, 450, 145, 23);

        tabelmhs2.setAutoCreateRowSorter(true);
        tabelmhs2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tabelmhs2);

        jPanel8.add(jScrollPane6);
        jScrollPane6.setBounds(430, 310, 614, 184);

        Mhs_cari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mhs_cariActionPerformed(evt);
            }
        });
        jPanel8.add(Mhs_cari2);
        Mhs_cari2.setBounds(170, 310, 126, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Cari Mahasiswa");
        jPanel8.add(jLabel26);
        jLabel26.setBounds(40, 310, 110, 30);

        cari_mhs2.setText("CARI");
        cari_mhs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_mhsActionPerformed(evt);
            }
        });
        jPanel8.add(cari_mhs2);
        cari_mhs2.setBounds(170, 360, 57, 23);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("CARI DATA MAHASISWA");
        jPanel8.add(jLabel23);
        jLabel23.setBounds(390, 130, 460, 104);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/perpustera.png"))); // NOI18N
        jPanel8.add(jLabel4);
        jLabel4.setBounds(-10, -20, 1150, 660);

        javax.swing.GroupLayout tampildatamhsLayout = new javax.swing.GroupLayout(tampildatamhs);
        tampildatamhs.setLayout(tampildatamhsLayout);
        tampildatamhsLayout.setHorizontalGroup(
            tampildatamhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tampildatamhsLayout.setVerticalGroup(
            tampildatamhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        getContentPane().add(tampildatamhs, "card4");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        cancelMenudosen.setText("CANCEL");
        cancelMenudosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelMenudosenActionPerformed(evt);
            }
        });
        jPanel4.add(cancelMenudosen);
        cancelMenudosen.setBounds(170, 410, 90, 23);

        tabledosen.setAutoCreateRowSorter(true);
        tabledosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabledosen);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(460, 240, 614, 187);

        dosen_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosen_cariActionPerformed(evt);
            }
        });
        jPanel4.add(dosen_cari);
        dosen_cari.setBounds(170, 270, 140, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cari Dosen");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(60, 280, 90, 20);

        cari_anggota.setText("CARI");
        cari_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_anggotaActionPerformed(evt);
            }
        });
        jPanel4.add(cari_anggota);
        cari_anggota.setBounds(170, 330, 57, 23);

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("CARI DATA DOSEN");
        jPanel4.add(jLabel34);
        jLabel34.setBounds(390, 130, 369, 104);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/perpustera.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(0, 0, 1220, 640);

        javax.swing.GroupLayout tampildatadosenLayout = new javax.swing.GroupLayout(tampildatadosen);
        tampildatadosen.setLayout(tampildatadosenLayout);
        tampildatadosenLayout.setHorizontalGroup(
            tampildatadosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tampildatadosenLayout.setVerticalGroup(
            tampildatadosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(tampildatadosen, "card5");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        cancelMenuPinjam.setText("CANCEL");
        cancelMenuPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelMenuPinjamActionPerformed(evt);
            }
        });
        jPanel5.add(cancelMenuPinjam);
        cancelMenuPinjam.setBounds(362, 547, 145, 23);

        tabelpinjam.setAutoCreateRowSorter(true);
        tabelpinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabelpinjam);

        jPanel5.add(jScrollPane3);
        jScrollPane3.setBounds(130, 280, 901, 200);

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("PEMINJAMAN BUKU");
        jPanel5.add(jLabel35);
        jLabel35.setBounds(470, 150, 369, 104);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/perpustera.png"))); // NOI18N
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel5.add(jLabel8);
        jLabel8.setBounds(0, -6, 1140, 680);

        javax.swing.GroupLayout peminjamanLayout = new javax.swing.GroupLayout(peminjaman);
        peminjaman.setLayout(peminjamanLayout);
        peminjamanLayout.setHorizontalGroup(
            peminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        peminjamanLayout.setVerticalGroup(
            peminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
        );

        getContentPane().add(peminjaman, "card6");

        setSize(new java.awt.Dimension(1152, 665));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void caribukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caribukuMouseClicked
        // TODO add your handling code here:
        tampilDataBuku.setVisible(true);
        Menuawal.setVisible(false);

        TableBuku a = new TableBuku(jTable1);
        a.getData();

    }//GEN-LAST:event_caribukuMouseClicked

    private void pinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinjamMouseClicked
        Menuawal.setVisible(false);
        peminjaman.setVisible(true);
        
        TablePeminjaman a = new TablePeminjaman(tabelpinjam);
        a.getData();
    }//GEN-LAST:event_pinjamMouseClicked

    private void carimhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carimhsMouseClicked
        Menuawal.setVisible(false);
        tampildatamhs.setVisible(true);
        
        TableMahasiswa a = new TableMahasiswa(tabelmhs2);
        a.getData();
    }//GEN-LAST:event_carimhsMouseClicked

    private void caridosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caridosenMouseClicked
        tampildatadosen.setVisible(true);
        Menuawal.setVisible(false);
        
        TableDosen a = new TableDosen(tabledosen);
        a.getData();
    }//GEN-LAST:event_caridosenMouseClicked

    private void cancelMeuTampilBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelMeuTampilBukuActionPerformed
        // TODO add your handling code here:
        tampilDataBuku.setVisible(false);
        Menuawal.setVisible(true);
    }//GEN-LAST:event_cancelMeuTampilBukuActionPerformed

    private void cari_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_bukuActionPerformed
        // TODO add your handling code here:
        tampilDataBuku.setVisible(true);
        Menuawal.setVisible(false);

        TableBuku a = new TableBuku(jTable1);
        a.getCari(caribuku_.getText());
        caribuku_.setText("");
    }//GEN-LAST:event_cari_bukuActionPerformed

    private void logoutmhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutmhsMouseClicked
        new login1().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutmhsMouseClicked

    private void cancelMeuMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelMeuMhsActionPerformed

        Menuawal.setVisible(true);
        tampildatamhs.setVisible(false);
    }//GEN-LAST:event_cancelMeuMhsActionPerformed

    private void Mhs_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mhs_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mhs_cariActionPerformed

    private void cari_mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_mhsActionPerformed
        // TODO add your handling code here:
        Menuawal.setVisible(false);
        tampildatamhs.setVisible(true);

        TableMahasiswa a = new TableMahasiswa(tabelmhs2);
        a.getCari(Mhs_cari2.getText());
        Mhs_cari2.setText("");
    }//GEN-LAST:event_cari_mhsActionPerformed

    private void cancelMenudosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelMenudosenActionPerformed
        // TODO add your handling code here:
        Menuawal.setVisible(true);
        tampildatadosen.setVisible(false);
    }//GEN-LAST:event_cancelMenudosenActionPerformed

    private void dosen_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosen_cariActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_dosen_cariActionPerformed

    private void cari_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_anggotaActionPerformed
        // TODO add your handling code here:
        Menuawal.setVisible(false);
        tampildatadosen.setVisible(true);

        TableDosen a = new TableDosen(tabledosen);
        a.getCari(dosen_cari.getText());
        dosen_cari.setText("");
    }//GEN-LAST:event_cari_anggotaActionPerformed

    private void cancelMenuPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelMenuPinjamActionPerformed
        // TODO add your handling code here:
        Menuawal.setVisible(true);
        peminjaman.setVisible(false);
    }//GEN-LAST:event_cancelMenuPinjamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menuawal;
    private javax.swing.JTextField Mhs_cari2;
    private javax.swing.JButton cancelMenuPinjam;
    private javax.swing.JButton cancelMenudosen;
    private javax.swing.JButton cancelMeuMhs2;
    private javax.swing.JButton cancelMeuTampilBuku;
    private javax.swing.JButton cari_anggota;
    private javax.swing.JButton cari_buku;
    private javax.swing.JButton cari_mhs2;
    private javax.swing.JLabel caribuku;
    private javax.swing.JTextField caribuku_;
    private javax.swing.JLabel caridosen;
    private javax.swing.JLabel carimhs;
    private javax.swing.JTextField dosen_cari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logoutmhs;
    private javax.swing.JPanel peminjaman;
    private javax.swing.JLabel pinjam;
    private javax.swing.JTable tabelmhs2;
    private javax.swing.JTable tabelpinjam;
    private javax.swing.JTable tabledosen;
    private javax.swing.JPanel tampilDataBuku;
    private javax.swing.JPanel tampildatadosen;
    private javax.swing.JPanel tampildatamhs;
    // End of variables declaration//GEN-END:variables
}
